
name: HUNTECH Backend Apply

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'infra/backend/**'
      - 'backend/handlers/**'
      - '.github/workflows/backend-apply.yml'

jobs:
  apply:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      AWS_REGION: us-east-1
      ROLE_TO_ASSUME: arn:aws:iam::382773571217:role/HUNTECH-CICD
      TF_IN_AUTOMATION: "true"

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Resolve Cognito issuer & audience
        id: cognito
        run: |
          set -e
          POOL_NAME="HUNTECH-auth-dev"
          REGION="${AWS_REGION}"
          # Find user pool id
          POOL_ID=$(aws cognito-idp list-user-pools --max-results 60 --query "UserPools[?Name=='${POOL_NAME}'].Id | [0]" --output text)
          if [ -z "$POOL_ID" ] || [ "$POOL_ID" = "None" ]; then
            echo "::error::Cognito user pool '${POOL_NAME}' not found in ${REGION}"; exit 1
          fi
          # Ensure a public app client exists (no secret)
          CLIENT_ID=$(aws cognito-idp list-user-pool-clients --user-pool-id "$POOL_ID" --max-results 60 --query 'UserPoolClients[0].ClientId' --output text || true)
          if [ -z "$CLIENT_ID" ] || [ "$CLIENT_ID" = "None" ]; then
            CLIENT_ID=$(aws cognito-idp create-user-pool-client --user-pool-id "$POOL_ID" --client-name huntech-public-web --generate-secret false --query 'UserPoolClient.ClientId' --output text)
          fi
          ISSUER="https://cognito-idp.${REGION}.amazonaws.com/${POOL_ID}"
          echo "issuer=$ISSUER"   >> $GITHUB_OUTPUT
          echo "audience=$CLIENT_ID" >> $GITHUB_OUTPUT

      - name: Terraform init
        working-directory: infra/backend
        run: terraform init -input=false -upgrade

      - name: Terraform apply (backend)
        working-directory: infra/backend
        env:
          TF_VAR_cognito_issuer: ${{ steps.cognito.outputs.issuer }}
          TF_VAR_cognito_audience: ${{ steps.cognito.outputs.audience }}
        run: terraform apply -auto-approve

      - name: Output API endpoint
        id: out
        working-directory: infra/backend
        run: |
          EP=$(terraform output -raw api_endpoint)
          echo "api=$EP" >> $GITHUB_OUTPUT
          echo "API: $EP"
