AWSTemplateFormatVersion: '2010-09-09'
Description: HUNTECH Foundation (dev) - API Gateway (HTTP), Lambda, DynamoDB, S3 (web/media), EventBridge, Secrets, CloudWatch

Parameters:
  ProjectName:
    Type: String
    Default: HUNTECH
  Environment:
    Type: String
    Default: dev
  CreateApiAuthorizer:
    Type: String
    AllowedValues: ['true','false']
    Default: 'false'
  CognitoUserPoolArn:
    Type: String
    Default: ''
    Description: Optional. Provide ARN only if CreateApiAuthorizer=true.

Conditions:
  UseAuthorizer: !And
    - !Equals [ !Ref CreateApiAuthorizer, 'true' ]
    - !Not [ !Equals [ !Ref CognitoUserPoolArn, '' ] ]

Resources:
  # ------------------- S3 Buckets (private, versioned, SSE) -------------------
  WebBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'huntech-web-${AWS::AccountId}-${AWS::Region}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  MediaBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'huntech-media-${AWS::AccountId}-${AWS::Region}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  # ------------------- DynamoDB -------------------
  AppTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-${Environment}-AppData'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE

  # ------------------- IAM Role for Lambda -------------------
  AppFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-${Environment}-LambdaRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: AppTableAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:UpdateItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource: !GetAtt AppTable.Arn
        - PolicyName: MediaBucketAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
