AWSTemplateFormatVersion: '2010-09-09'
Description: HUNTECH Foundation (dev) - API Gateway (HTTP), Lambda, DynamoDB, S3 (web/media), EventBridge, Secrets, CloudWatch

Parameters:
  ProjectName:
    Type: String
    Default: HUNTECH
  Environment:
    Type: String
    Default: dev
  WebBucketName:
    Type: String
    Default: !Sub 'huntech-web-${AWS::AccountId}-${AWS::Region}'
    Description: S3 bucket for static web/media assets (served via CloudFront later)
  MediaBucketName:
    Type: String
    Default: !Sub 'huntech-media-${AWS::AccountId}-${AWS::Region}'
    Description: S3 bucket for user uploads/media
  DynamoTableName:
    Type: String
    Default: !Sub '${ProjectName}-${Environment}-AppData'
  CreateApiAuthorizer:
    Type: String
    AllowedValues: ['true','false']
    Default: 'false'
  CognitoUserPoolArn:
    Type: String
    Default: ''
    Description: Optional. Provide ARN only if CreateApiAuthorizer=true.

Conditions:
  UseAuthorizer: !And [ !Equals [ !Ref CreateApiAuthorizer, 'true' ], !Not [ !Equals [ !Ref CognitoUserPoolArn, '' ] ] ]

Resources:
  # ------------------- S3 Buckets -------------------
  WebBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref WebBucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
  MediaBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref MediaBucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled

  # ------------------- DynamoDB -------------------
  AppTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref DynamoTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE

  # ------------------- IAM Role for Lambda -------------------
  AppFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-${Environment}-LambdaRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: AppTableAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:UpdateItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource: !GetAtt AppTable.Arn
        - PolicyName: MediaBucketAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:DeleteObject
                Resource: !Sub '${MediaBucket.Arn}/*'

  # ------------------- Lambda Function -------------------
  AppFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-${Environment}-ApiHandler'
      Description: Minimal handler (health + put/get sample)
      Runtime: python3.12
      Handler: index.handler
      Role: !GetAtt AppFunctionRole.Arn
      Timeout: 15
      MemorySize: 256
      Environment:
        Variables:
          TABLE_NAME: !Ref DynamoTableName
          MEDIA_BUCKET: !Ref MediaBucketName
      Code:
        ZipFile: !Sub |
          import json, os, boto3
          ddb = boto3.resource('dynamodb')
          s3 = boto3.client('s3')
          table = ddb.Table(os.environ['TABLE_NAME'])

          def handler(event, context):
              path = event.get('rawPath','/')
              if path == '/health':
                  return { 'statusCode': 200, 'headers': {'content-type':'application/json'}, 'body': json.dumps({'ok': True}) }
              if path == '/seed':
                  table.put_item(Item={'pk':'DEMO','sk':'SEED','ts':context.aws_request_id})
                  return { 'statusCode': 200, 'headers': {'content-type':'application/json'}, 'body': json.dumps({'seeded': True}) }
              return { 'statusCode': 404, 'headers': {'content-type':'application/json'}, 'body': json.dumps({'error':'Not Found'}) }

  # ------------------- API Gateway (HTTP) -------------------
  HttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub '${ProjectName}-${Environment}-HttpApi'
      ProtocolType: HTTP

  # Optional Authorizer (Cognito)
  HttpAuthorizer:
    Type: AWS::ApiGatewayV2::Authorizer
    Condition: UseAuthorizer
    Properties:
      ApiId: !Ref HttpApi
      AuthorizerType: JWT
      IdentitySource:
        - '$request.header.Authorization'
      Name: CognitoJwt
      JwtConfiguration:
        Audience:
          - sts.amazonaws.com
        Issuer: !Sub '${CognitoUserPoolArn}'

  # Integration and Routes
  HttpIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AppFunction.Arn}/invocations'
      PayloadFormatVersion: '2.0'

  RouteHealth:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'GET /health'
      Target: !Sub 'integrations/${HttpIntegration}'

  StageDefault:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref HttpApi
      StageName: '$default'
      AutoDeploy: true

  # Permission for API GW to invoke Lambda
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref AppFunction
      Principal: apigateway.amazonaws.com

  # ------------------- EventBridge (optional heartbeat) -------------------
  HeartbeatRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub '${ProjectName}-${Environment}-Heartbeat'
      ScheduleExpression: rate(30 minutes)
      State: ENABLED
      Targets:
        - Arn: !GetAtt AppFunction.Arn
          Id: AppFn
  HeartbeatInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref AppFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt HeartbeatRule.Arn

  # ------------------- Secrets Manager (placeholder) -------------------
  VendorKeys:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${ProjectName}/${Environment}/TrailCam/VendorKeys'
      Description: Placeholder for partner API keys
      SecretString: '{}'

Outputs:
  ApiEndpoint:
    Description: Invoke URL of the HTTP API (default stage)
    Value: !Sub 'https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com'
  WebBucketOut:
    Value: !Ref WebBucketName
  MediaBucketOut:
    Value: !Ref MediaBucketName
  DynamoTableOut:
    Value: !Ref DynamoTableName
  FunctionName:
    Value: !Ref AppFunction
``
